
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY ./src/Api/src/Api/Api.csproj ./Api/src/Api/
RUN dotnet restore ./Api/src/Api/Api.csproj

# copy everything else and build app
COPY ./src/Api/src/Api/ ./Api/src/Api/

WORKDIR /Api/src/Api
RUN dotnet publish -c Release  -o out

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build ./Api/src/Api/out .

ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT ["dotnet", "Api.dll"]