
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY ./src/Web/src/Web/Web.csproj ./Web/src/Web/
RUN dotnet restore ./Web/src/Web/Web.csproj

# copy everything else and build app
COPY ./src/Web/src/Web/ ./Web/src/Web/
RUN dotnet build  -c Release --no-restore ./Web/src/Web/Web.csproj

WORKDIR /Web/src/Web
RUN dotnet publish -c Release --no-build -o out

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build ./Web/src/Web/out .

ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT ["dotnet", "Web.dll"]